baseURL: 'https://tsaklidou.github.io/'
languageCode: 'en-us'
title: 'Sofia Tsaklidou'

params:
  author: "Sofia Tsaklidou"
  tagline: "AI Engineer & Data Scientist" 
  description: "Building intelligent solutions with AI & Data Science."
  github: "https://github.com/tsaklidou"
  linkedin: "https://linkedin.com/in/tsaklidou"